DROP TABLE borbotones.orientacion
DROP TABLE borbotones.caracteristica
DROP TABLE borbotones.inmueble
DROP TABLE borbotones.ambientes 
DROP TABLE borbotones.caracteristicaporinmueble
DROP TABLE borbotones.persona
DROP TABLE borbotones.agente
DROP TABLE borbotones.propietario
DROP TABLE borbotones.moneda
DROP TABLE borbotones.mediodepago
DROP TABLE borbotones.tiposperiodosanuncio
DROP TABLE borbotones.estadoanuncio
DROP TABLE borbotones.tipooperacion
DROP TABLE borbotones.anuncio
DROP TABLE borbotones.estadoalquiler
DROP TABLE borbotones.alquiler
DROP TABLE borbotones.importeporperiodos
DROP TABLE borbotones.pagoalquiler
DROP TABLE borbotones.inquilino
DROP TABLE borbotones.venta
DROP TABLE borbotones.comprador
DROP TABLE borbotones.pagoventa
DROP TABLE borbotones.sucursal
DROP TABLE borbotones.tipoinmueble
DROP TABLE borbotones.estadoinmueble
DROP TABLE borbotones.disposicion
DROP TABLE borbotones.provincia
DROP TABLE borbotones.localidad
DROP TABLE borbotones.barrio