DROP TABLE orientacion
DROP TABLE caracteristica
DROP TABLE inmueble
DROP TABLE ambientes 
DROP TABLE caracteristicaporinmueble
DROP TABLE persona
DROP TABLE agente
DROP TABLE propietario
DROP TABLE moneda
DROP TABLE mediodepago
DROP TABLE tiposperiodosanuncio
DROP TABLE estadoanuncio
DROP TABLE tipooperacion
DROP TABLE anuncio
DROP TABLE estadoalquiler
DROP TABLE alquiler
DROP TABLE importeporperiodos
DROP TABLE pagoalquiler
DROP TABLE inquilino
DROP TABLE venta
DROP TABLE comprador
DROP TABLE pagoventa
DROP TABLE sucursal
DROP TABLE tipoinmueble
DROP TABLE estadoinmueble
DROP TABLE disposicion
DROP TABLE provincia
DROP TABLE localidad
DROP TABLE barrio
drop table estadoanuncio